
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='xe_likelihood',
    version='0.1.0',
    description='Top-level package for xe-likelihood.',
    python_requires='==3.*,>=3.7.1',
    project_urls={"homepage": "https://github.com/XENON1T/xe_likelihood"},
    author='XENON collaboration',
    author_email='knut.dundas.moraa@columbia.edu',
    maintainer='Hagar Landsman',
    maintainer_email='hagar.landsman@weizmann.ac.il',
    license='MIT',
    classifiers=['Development Status :: 2 - Pre-Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: MIT License', 'Natural Language :: English', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8'],
    entry_points={"console_scripts": ["xe-likelihood = xe_likelihood.cli:main"]},
    packages=['xe_likelihood', 'xe_likelihood.data', 'xe_likelihood.data.ancillary_data', 'xe_likelihood.data.xe1t_nr_1ty_result', 'xe_likelihood.data.xent_nr_20ty_projection'],
    package_dir={"": "."},
    package_data={"xe_likelihood.data.ancillary_data": ["*.csv"], "xe_likelihood.data.xe1t_nr_1ty_result": ["*.json"], "xe_likelihood.data.xent_nr_20ty_projection": ["*.gz", "*.json"]},
    install_requires=['click==8.*,>=8.0.3', 'matplotlib', 'numpy', 'pandas!=1.3.4', 'scipy', 'tqdm'],
    extras_require={"dev": ["bumpversion", "coverage", "docutils==0.12", "flake8", "invoke", "isort", "jupyter", "jupyterlab", "nbsphinx==0.8.3", "pylint", "pytest", "sphinx", "sphinx-material", "tox", "yapf"], "wimps": ["wimprates==0.*,>=0.3.2"]},
)
